### ISSUE TITLE
[BUG] Build doesn't work because of not-working repository

### ISSUE THREAD

**Issue by LeStegii** [CrucibleMC/Crucible#123] opened 2023-01-07 12:10 UTC
It's currently not possible to run `setupCrucible`. For more information check #119.

```cmd
$ ./gradlew clean setupCrucible
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
[Fatal Error] argo-2.25.pom:3:10: doctype bereits gesehen.
[Fatal Error] argo-2.25.pom:3:10: doctype bereits gesehen.
#####################################################
       ForgeGradle 1.2-1.5.5-SNAPSHOT-3c2244ae
     https://github.com/juanmuscaria/ForgeGradle
#####################################################
                    Powered by MCP
               http://modcoderpack.com
           by: Searge, ProfMobius, Fesh0r,
           R4wk, ZeuX, IngisKahn, bspkrs

                     Reissued by:
              juanmuscaria, Aizistral
#####################################################

> Task :getAssetsIndex
Unexpected reponse 403 from https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json

> Task :downloadClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadClient'.
> java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

**Comment by paulzzh** [comment] 2023-01-25 16:16
https://github.com/GTNewHorizons/ForgeGradle/commit/1d04030a1f3b7b7b220f73d8019944ba29a7d017

**Comment by juanmuscaria** [comment] 2023-01-25 16:18
Duplicate of #120

**Closed as completed by juanmuscaria** 2023-01-25 16:18 UTC
Labels: bug, duplicate
