### ISSUE TITLE
Server does not unload worlds.

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Crucible#16] opened 2020-03-04 05:59 UTC
Tested on 3 different servers, even with the cauldron.yml having keep-loaded to false worlds remain loaded.

![Screenshot_391](https://user-images.githubusercontent.com/3002248/75849649-3bedac00-5d9a-11ea-9ae2-384f3c43aeed.png)

**Comment by juanmuscaria** [comment] 2020-03-13 00:56
it’s really strange, the worlds are still loaded in memory, but it don’t get ticked (it only gets the ticked to update time and weather), but I don’t know if it’s intentional cauldron/thermos behavior.
Cauldron/Thermos has a lot of weird stuff in the middle of the code that I have no idea what it does, I'll leave this issue marked as a bug until I found out if this is intentional behavior or not

**Comment by spannerman79** [comment] 2020-03-13 08:05
I this is intended behavour on the forge side of things.

For exmaple;
Spirit World is part of [Witchery](https://sites.google.com/site/witcherymod/spirit-world).  Trying to force unload that world creates an unintentional memroy leak especially if you have players that have accessed the dream world & have left the required TE's (can't remember the blocks) behind to use later on. As that DIM has two states (dream/nightmare) it depends on that world to be loaded.

>Cauldron/Thermos has a lot of weird stuff in the middle of the code that I have no idea what it does

Best way to see it is that its a forge server with some bukkit api sprinkled in.  Don't depend on the bukkit side of the things too much (ie force unloading worlds) and shit won't break.

**Comment by evernife** [comment] 2020-03-13 23:33
@Zilacon have you felt a great impact on TPS because of this? 
How ofter do you restart your server?

**Comment by Zilacon** [comment] 2020-03-13 23:38
This IS NOT an issue on Thermos. So this is definitely a Crucible problem.
I restart my servers every 6 hours.
And its kinda hard to tell what the tps impact of that is when you have 100+ mods loaded on the server. But since they are loaded, and ticking, its got some impact.

**Comment by evernife** [comment] 2020-04-25 05:33
Our source: https://github.com/CrucibleMC/Crucible/blob/master/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L1066-L1087

Thermos Source:
https://github.com/CyberdyneCC/Thermos/blob/bae97f16f0fac984a56083769ef75cb8a8eb1812/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L1000-L1017

Probably this is the cause:

```
 if (!(handle.dimension > 1)) {
            return false;
        }
```

Needs testing.

**Comment by juanmuscaria** [comment] 2020-04-25 14:37
Here a test build with all my recent commits https://www.dropbox.com/s/01t7kcxscm2c9bs/Crucible-1.7.10-TEST-BUILD-server.jar?dl=0
See if the problem persists.

**Comment by juanmuscaria** [comment] 2020-04-25 22:16
![Screenshot_1](https://user-images.githubusercontent.com/34891068/80292022-2f962780-8729-11ea-8a2c-1b6127c14320.png)
It seems to be working on this test build, I'll be closing this issue for now.

**Closed by juanmuscaria** 2020-04-25 22:16 UTC
Labels: In Progress, bug
